# Generated by Django 5.2.8 on 2025-11-11 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 7, 30, 20, 287966, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
