# Generated by Django 5.2.8 on 2025-11-11 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_organization_industry_alter_usertoken_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="industry",
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 7, 32, 30, 790294, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
