# Generated by Django 5.2.8 on 2025-11-11 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_organization_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 11, 8, 12, 2, 168873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
